using System.Security;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;

namespace DarkestDungeonSaveEditor.Core;

public sealed record BattleEncounterBridgePackage(
    string PackageDirectory,
    string ProjectTitle,
    string MashFilePath,
    string ManifestPath,
    int MashType,
    int ExpectedMashIndex,
    IReadOnlyList<string> MonsterIds,
    string SourceTableFingerprint,
    string GeneratedMashSha256)
{
    public string OriginDungeonId { get; init; } = string.Empty;

    public int OriginDifficulty { get; init; }

    public BattleEncounterSourceKind SourceKind { get; init; }
}

public static class BattleEncounterBridgeBuilder
{
    private static readonly UTF8Encoding Utf8NoBom = new(false);
    private const string BridgeTitlePrefix = "DDSE Encounter Bridge - ";

    public static BattleEncounterBridgePackage Build(
        BattleEncounterCatalogResult catalog,
        BattleEncounterDefinition encounter,
        string? outputRoot = null)
    {
        ArgumentNullException.ThrowIfNull(catalog);
        ArgumentNullException.ThrowIfNull(encounter);
        if (!encounter.TableGuard.Fingerprint.Equals(
                catalog.TableGuard.Fingerprint,
                StringComparison.OrdinalIgnoreCase))
        {
            throw new InvalidOperationException("所选遭遇不属于当前遭遇目录快照。");
        }
        if (catalog.TableGuard.ActiveSources.Any(IsGeneratedBridgeSource))
        {
            throw new InvalidOperationException(
                "当前档案已经启用另一个 DDSE Encounter Bridge。请先完成或删除其遭遇，" +
                "确认地图与战斗不再引用新增索引，再禁用旧 Bridge 并重新加载内容目录。");
        }

        BattleEncounterCatalog.ValidateBridgeEncounter(encounter);
        var target = BattleEncounterCatalog.ResolveAppendTarget(catalog, encounter.MashType);
        var expectedMashIndex = target.NextMashIndex;
        var sourceTableFingerprint = catalog.TableGuard.Fingerprint;

        outputRoot ??= Path.Combine(
            SaveEditorLocations.CreateDefault().WorkspaceDirectory,
            "encounter_bridge");
        outputRoot = Path.GetFullPath(outputRoot);
        Directory.CreateDirectory(outputRoot);
        var encounterSlug = CreateSlug(string.Join("_", encounter.MonsterIds));
        var sessionId = $"{DateTime.UtcNow:yyyyMMdd_HHmmss_fff}_{Guid.NewGuid():N}";
        var projectTitle =
            $"{BridgeTitlePrefix}{catalog.DungeonId} {catalog.Difficulty} - {encounterSlug}";
        var packageName = projectTitle;
        var packageDirectory = Path.Combine(outputRoot, sessionId, packageName);
        if (Directory.Exists(packageDirectory))
        {
            throw new IOException($"Bridge 输出目录已经存在：{packageDirectory}");
        }

        var relativeMashPath = target.RelativeMashPath;
        var mashFilePath = Path.Combine(
            packageDirectory,
            relativeMashPath.Replace('/', Path.DirectorySeparatorChar));
        Directory.CreateDirectory(Path.GetDirectoryName(mashFilePath)!);
        var appendedLine = EncounterBridgeRow.Format(encounter.MashType, encounter.MonsterIds);
        var appendedBytes = Utf8NoBom.GetBytes(appendedLine);
        using (var output = new FileStream(
                   mashFilePath,
                   FileMode.CreateNew,
                   FileAccess.Write,
                   FileShare.None))
        {
            output.Write(appendedBytes);
            output.Flush(flushToDisk: true);
        }

        var projectPath = Path.Combine(packageDirectory, "project.xml");
        var modDataPath = packageDirectory.Replace('\\', '/').TrimEnd('/') + "/";
        EncounterBridgeBranding.WritePreview(packageDirectory);
        File.WriteAllText(
            projectPath,
            $"""
            <?xml version="1.0" encoding="utf-8"?>
            <project>
              <PreviewIconFile>{SecurityElement.Escape(modDataPath + EncounterBridgeBranding.PreviewFileName)}</PreviewIconFile>
              <ItemDescriptionShort>Deterministic encounter carrier generated for one active expedition table.</ItemDescriptionShort>
              <ModDataPath>{SecurityElement.Escape(modDataPath)}</ModDataPath>
              <Title>{SecurityElement.Escape(projectTitle)}</Title>
              <Language>english</Language>
              <Visibility>private</Visibility>
              <UploadMode>direct_upload</UploadMode>
              <VersionMajor>0</VersionMajor>
              <VersionMinor>0</VersionMinor>
              <TargetBuild>0</TargetBuild>
              <Tags><Tags>Gameplay Tweaks</Tags></Tags>
              <ItemDescription>Local Encounter Bridge generated by Darkest Dungeon Save Editor. Keep enabled while any save still references its appended mash index.</ItemDescription>
              <PublishedFileId>0</PublishedFileId>
            </project>
            """,
            Utf8NoBom);

        var manifestPath = Path.Combine(packageDirectory, "ddse-encounter-bridge.json");
        var generatedMashSha256 = ComputeSha256(mashFilePath);
        File.WriteAllText(
            manifestPath,
            JsonSerializer.Serialize(
                new
                {
                    version = 3,
                    generatedAtUtc = DateTime.UtcNow,
                    catalog.DungeonId,
                    catalog.Difficulty,
                    mashType = encounter.MashType,
                    expectedMashIndex,
                    monsterIds = encounter.MonsterIds,
                    sourceKind = encounter.SourceKind.ToString(),
                    originDungeonId = encounter.OriginDungeonId,
                    originDifficulty = encounter.OriginDifficulty,
                    roamingId = encounter.RoamingId,
                    sourceLabel = encounter.SourceLabel,
                    sourcePath = encounter.SourcePath,
                    sourceRelativePath = encounter.SourceRelativePath,
                    sourceLine = encounter.SourceLine,
                    sourceRecordIndex = encounter.SourceRecordIndex,
                    sourceTableFingerprint,
                    generatedMashPath = relativeMashPath,
                    generatedMashSha256,
                    tableFingerprint = catalog.TableGuard.Fingerprint,
                    appendedLine = appendedLine.Trim()
                },
                JsonSupport.SerializerOptions),
            Utf8NoBom);
        File.WriteAllText(
            Path.Combine(packageDirectory, "modfiles.txt"),
            $"{relativeMashPath} {new FileInfo(mashFilePath).Length}" + Environment.NewLine +
            $"{EncounterBridgeBranding.PreviewFileName} {new FileInfo(Path.Combine(packageDirectory, EncounterBridgeBranding.PreviewFileName)).Length}" + Environment.NewLine,
            Utf8NoBom);

        return new BattleEncounterBridgePackage(
            packageDirectory,
            projectTitle,
            mashFilePath,
            manifestPath,
            encounter.MashType,
            expectedMashIndex,
            encounter.MonsterIds,
            sourceTableFingerprint,
            generatedMashSha256)
        {
            OriginDungeonId = encounter.OriginDungeonId,
            OriginDifficulty = encounter.OriginDifficulty,
            SourceKind = encounter.SourceKind
        };
    }

    private static bool IsGeneratedBridgeSource(ActiveContentSource source) =>
        source.DisplayName.StartsWith("DDSE Encounter Bridge", StringComparison.OrdinalIgnoreCase) ||
        File.Exists(Path.Combine(source.Directory, "ddse-encounter-bridge.json")) ||
        File.Exists(Path.Combine(source.Directory, "ddse-encounter-bridge-probe.json"));

    private static string CreateSlug(string value)
    {
        var result = new StringBuilder(value.Length);
        foreach (var character in value.Trim())
        {
            result.Append(char.IsLetterOrDigit(character) || character is '-' or '_'
                ? character
                : '_');
        }

        var slug = result.ToString().Trim('_');
        if (slug.Length == 0)
        {
            slug = "encounter";
        }
        const int readableLength = 36;
        if (slug.Length > readableLength)
        {
            slug = slug[..readableLength].TrimEnd('_');
        }

        var hash = Convert.ToHexString(
            SHA256.HashData(Encoding.UTF8.GetBytes(value))).ToLowerInvariant()[..8];
        return $"{slug}-{hash}";
    }

    private static string ComputeSha256(string path)
    {
        using var stream = File.OpenRead(path);
        return Convert.ToHexString(SHA256.HashData(stream)).ToLowerInvariant();
    }
}

public static class BattleEncounterBridgeProbeBuilder
{
    public static BattleEncounterBridgePackage Build(
        BattleEncounterCatalogResult catalog,
        BattleEncounterDefinition encounter,
        string? outputRoot = null) =>
        BattleEncounterBridgeBuilder.Build(catalog, encounter, outputRoot);
}
